# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stick_detection_params.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StickDetectionParams(object):
    def setupUi(self, StickDetectionParams):
        StickDetectionParams.setObjectName("StickDetectionParams")
        StickDetectionParams.resize(664, 518)
        self.horizontalLayout = QtWidgets.QHBoxLayout(StickDetectionParams)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.spinWidth = QtWidgets.QSpinBox(StickDetectionParams)
        self.spinWidth.setMinimum(2)
        self.spinWidth.setSingleStep(2)
        self.spinWidth.setProperty("value", 2)
        self.spinWidth.setObjectName("spinWidth")
        self.gridLayout.addWidget(self.spinWidth, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(StickDetectionParams)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.paramsText = QtWidgets.QPlainTextEdit(StickDetectionParams)
        self.paramsText.setObjectName("paramsText")
        self.gridLayout.addWidget(self.paramsText, 4, 1, 1, 1)
        self.spinSensitivity = QtWidgets.QDoubleSpinBox(StickDetectionParams)
        self.spinSensitivity.setMinimum(0.1)
        self.spinSensitivity.setMaximum(5.0)
        self.spinSensitivity.setProperty("value", 2.5)
        self.spinSensitivity.setObjectName("spinSensitivity")
        self.gridLayout.addWidget(self.spinSensitivity, 3, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(StickDetectionParams)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 7, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(StickDetectionParams)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(StickDetectionParams)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.spinLength = QtWidgets.QSpinBox(StickDetectionParams)
        self.spinLength.setMinimum(2)
        self.spinLength.setMaximum(300)
        self.spinLength.setProperty("value", 2)
        self.spinLength.setObjectName("spinLength")
        self.gridLayout.addWidget(self.spinLength, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(StickDetectionParams)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.spinP0 = QtWidgets.QDoubleSpinBox(StickDetectionParams)
        self.spinP0.setDecimals(1)
        self.spinP0.setMaximum(1.0)
        self.spinP0.setSingleStep(0.1)
        self.spinP0.setProperty("value", 0.5)
        self.spinP0.setObjectName("spinP0")
        self.gridLayout.addWidget(self.spinP0, 2, 1, 1, 1)
        self.btnApply = QtWidgets.QPushButton(StickDetectionParams)
        self.btnApply.setObjectName("btnApply")
        self.gridLayout.addWidget(self.btnApply, 6, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(StickDetectionParams)
        self.buttonBox.accepted.connect(StickDetectionParams.accept)
        self.buttonBox.rejected.connect(StickDetectionParams.reject)
        QtCore.QMetaObject.connectSlotsByName(StickDetectionParams)

    def retranslateUi(self, StickDetectionParams):
        _translate = QtCore.QCoreApplication.translate
        StickDetectionParams.setWindowTitle(_translate("StickDetectionParams", "Dialog"))
        self.label_4.setText(_translate("StickDetectionParams", "Sensitivity"))
        self.label_3.setText(_translate("StickDetectionParams", "p0"))
        self.label_2.setText(_translate("StickDetectionParams", "Stick width"))
        self.label.setText(_translate("StickDetectionParams", "Stick length"))
        self.btnApply.setText(_translate("StickDetectionParams", "Apply"))
