# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CameraView(object):
    def setupUi(self, CameraView):
        CameraView.setObjectName("CameraView")
        CameraView.resize(985, 795)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(CameraView)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.splitter = QtWidgets.QSplitter(CameraView)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.image_list = QtWidgets.QTableView(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_list.sizePolicy().hasHeightForWidth())
        self.image_list.setSizePolicy(sizePolicy)
        self.image_list.setStyleSheet("padding: 0px;\n"
"border: 0px;")
        self.image_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.image_list.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.image_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.image_list.setShowGrid(False)
        self.image_list.setObjectName("image_list")
        self.image_list.horizontalHeader().setVisible(False)
        self.image_list.verticalHeader().setVisible(False)
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cam_view_placeholder = QtWidgets.QVBoxLayout()
        self.cam_view_placeholder.setObjectName("cam_view_placeholder")
        self.verticalLayout.addLayout(self.cam_view_placeholder)
        self.horizontalLayout_3.addWidget(self.splitter)

        self.retranslateUi(CameraView)
        QtCore.QMetaObject.connectSlotsByName(CameraView)

    def retranslateUi(self, CameraView):
        _translate = QtCore.QCoreApplication.translate
        CameraView.setWindowTitle(_translate("CameraView", "Form"))
